/* Create a table containing Fee data. */  
CREATE TABLE FEE (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID),
	FEE_VALUE float NOT NULL CHECK (FEE_VALUE >= -100 AND FEE_VALUE <= 100)
);
	
/* Create a table containing Category data. */
CREATE TABLE CATEGORY (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	FEE BIGINT,
	PRIMARY KEY (ID)
);

/* Create a table containing Poiuyt data. */
CREATE TABLE POIUYT (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

/* Create a join table for Category and Poiuyt data. */
CREATE TABLE CATEGORY_POIUYT (
    CATEGORY_ID BIGINT REFERENCES CATEGORY (ID),
    POIUYT_ID BIGINT REFERENCES POIUYT (ID),
    PRIMARY KEY (CATEGORY_ID, POIUYT_ID)
);