CREATE TABLE FEE (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID),
	FEE decimal(5,2) NOT NULL CHECK (FEE >= -100 AND FEE <= 100)
);

CREATE TABLE CATEGORY (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	FEE_ID BIGINT,
	PRIMARY KEY (ID),
	FOREIGN KEY (FEE_ID) REFERENCES FEE(ID)
);

CREATE TABLE POIUYT (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	CATEGORY_ID BIGINT,
	PRIMARY KEY (ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);